using System;
using System.Collections.Generic;

namespace WorldGen.Generation
{
    /// <summary>Fixture bench for the review fixes: every candidate fixture is run through the shipped packer AND
    /// through each MUTANT (a copy of the packer with exactly one rule removed, generated by sync.ps1). A new
    /// self-test assertion is non-vacuous iff its fixture's outcome differs between the two — that difference is
    /// what the numbers quoted in the self-test comments and the report come from.</summary>
    public static class Design
    {
        const int T = DungeonLayout.TilesPerAxis;
        static readonly float M = FloorFootprint.ContourMargin;

        public static Room R(int id, float tx, float ty, int w, int h)
            => new Room { Id = id, TypeId = 1, SizeW = w, SizeH = h, X = tx / T, Y = ty / T };

        public static InteriorFloor Clone(InteriorFloor f)
        {
            var c = new InteriorFloor { NextRoomId = f.NextRoomId };
            foreach (var r in f.Rooms) c.Rooms.Add(new Room { Id = r.Id, TypeId = r.TypeId, SizeW = r.SizeW, SizeH = r.SizeH, X = r.X, Y = r.Y });
            foreach (var l in f.Links) c.Links.Add(new Link { RoomA = l.RoomA, RoomB = l.RoomB });
            return c;
        }

        public static string Desc(InteriorFloor f, int kept)
        {
            var ids = new List<Room>(f.Rooms);
            ids.Sort((a, b) => a.Id.CompareTo(b.Id));
            string s = $"kept={kept}: ";
            foreach (var r in ids) s += $"[{r.Id}@({r.X * T:F2},{r.Y * T:F2}) {r.SizeW}x{r.SizeH}]";
            s += "  links:";
            foreach (var l in f.Links) s += $" {l.RoomA}-{l.RoomB}";
            return s;
        }

        delegate int PackFn(InteriorFloor floor, int columnId, float cx, float cy, InteriorFloor contour, float margin);

        static readonly (string name, PackFn fn)[] Variants =
        {
            ("SHIPPED",          CompactLayout.PackAroundColumnWithinFootprint),
            ("spread-only",      SpreadOnlyLayout.PackAroundColumnWithinFootprint),
            ("compact-only",     CompactOnlyLayout.PackAroundColumnWithinFootprint),
            ("as-reviewed",      PreReviewLayout.PackAroundColumnWithinFootprint),
            ("MUT anchor-outer", MutAnchorOuter.PackAroundColumnWithinFootprint),
            ("MUT no-link-pref", MutNoLinkPref.PackAroundColumnWithinFootprint),
            ("MUT tight-bounds", MutTightBounds.PackAroundColumnWithinFootprint),
            ("MUT no-dedup",     MutNoDedup.PackAroundColumnWithinFootprint),
            ("MUT fwd-dedup",    MutFwdDedupOnly.PackAroundColumnWithinFootprint),
        };

        public static void All(string name, InteriorFloor contour, InteriorFloor floor, float colX, float colY)
        {
            Console.WriteLine($"--- {name}  (column pinned at ({colX},{colY})) ---");
            foreach (var (vname, fn) in Variants)
            {
                var f = Clone(floor);
                int kept = fn(f, 1, colX, colY, Clone(contour), M);
                Console.WriteLine($"  {vname,-17} {Desc(f, kept)}");
            }
            var legacy = Clone(floor);
            Console.WriteLine($"  {"legacy (pre-F2)",-17} {Desc(legacy, LegacyPacker.Pack(legacy, 1, colX, colY, Clone(contour), M, false))}");
            var rev = Clone(floor); rev.Rooms.Reverse(); rev.Links.Reverse();
            Console.WriteLine($"  {"SHIPPED permuted",-17} {Desc(rev, CompactLayout.PackAroundColumnWithinFootprint(rev, 1, colX, colY, Clone(contour), M))}");
        }

        // ---- candidate fixtures ----------------------------------------------------------------------

        // M1: the zig-zag contour, re-derived so the three arms actually OVERLAP (the shipped one is
        // disconnected between arm 1 and arm 2, which the app's own CompactLayout.Arrange can never produce).
        public static InteriorFloor ZigZagContourConnected()
        {
            var c = new InteriorFloor { NextRoomId = 4 };
            c.Rooms.Add(R(1, 60, 56, 8, 4));    // [54.5,65.5] x [52.5,59.5]
            c.Rooms.Add(R(2, 56, 62, 4, 4));    // [52.5,59.5] x [58.5,65.5]   overlaps arm 1
            c.Rooms.Add(R(3, 60, 68, 4, 8));    // [56.5,63.5] x [62.5,73.5]   overlaps arm 2
            return c;
        }

        public static InteriorFloor ZigZagFloor()
        {
            var f = new InteriorFloor { NextRoomId = 5 };
            f.Rooms.Add(R(1, 60, 56, 4, 4)); f.Rooms.Add(R(2, 60, 56, 4, 4));
            f.Rooms.Add(R(3, 60, 56, 5, 4)); f.Rooms.Add(R(4, 60, 56, 5, 5));
            f.Links.Add(new Link { RoomA = 2, RoomB = 1 });
            f.Links.Add(new Link { RoomA = 3, RoomB = 2 });
            f.Links.Add(new Link { RoomA = 4, RoomB = 1 });
            return f;
        }

        // I6 / I2 bench: a long horizontal strip contour. RoomSizing.MaxSide is 16, so one room can only span
        // 16 tiles — two overlapping 16x4 rooms give [46.5,81.5] x [60.5,67.5]. Only a single row of 4-tall
        // rooms fits, so every placement is a pure left/right decision.
        public static InteriorFloor StripContour()
        {
            var c = new InteriorFloor { NextRoomId = 3 };
            c.Rooms.Add(R(1, 56, 64, 16, 4));   // [46.5,65.5] x [60.5,67.5]
            c.Rooms.Add(R(2, 72, 64, 16, 4));   // [62.5,81.5] x [60.5,67.5]
            return c;
        }

        // I4 bench: the same strip, shifted so the flush chain to the RIGHT of the column ends EXACTLY on the
        // footprint's outer edge — rooms at 68, 72, 76 put the last one's right edge at x = 78 = maxX.
        public static InteriorFloor EdgeStripContour()
        {
            var c = new InteriorFloor { NextRoomId = 3 };
            c.Rooms.Add(R(1, 60.5f, 64, 16, 4));   // [51,70]   x [60.5,67.5]
            c.Rooms.Add(R(2, 68.5f, 64, 16, 4));   // [59,78]   x [60.5,67.5]
            return c;
        }

        // True iff the contour's margin-expanded rects form ONE connected blob (each rect overlapping the next
        // with positive area) — CompactLayout.Arrange packs floor 0 flush, so a real contour is always connected.
        public static bool ContourConnected(InteriorFloor c, float margin)
        {
            int n = c.Rooms.Count;
            if (n == 0) return false;
            var seen = new bool[n];
            var stack = new Stack<int>(); stack.Push(0); seen[0] = true;
            int count = 1;
            (float x0, float y0, float x1, float y1) Box(Room r)
            {
                var (w, h) = DungeonProjection.EffectiveSize(r);
                float cx = r.X * T, cy = r.Y * T;
                return (cx - w * 0.5f - margin, cy - h * 0.5f - margin, cx + w * 0.5f + margin, cy + h * 0.5f + margin);
            }
            while (stack.Count > 0)
            {
                var a = Box(c.Rooms[stack.Pop()]);
                for (int j = 0; j < n; j++)
                {
                    if (seen[j]) continue;
                    var b = Box(c.Rooms[j]);
                    if (a.x0 < b.x1 && b.x0 < a.x1 && a.y0 < b.y1 && b.y0 < a.y1)
                    { seen[j] = true; count++; stack.Push(j); }
                }
            }
            return count == n;
        }

        /// <summary>Search small, hand-derivable fixtures on CONNECTED contours where the two runs disagree —
        /// both directions, since the review needs one of each (fixture C: spread wins; fixture D: compact wins).
        /// Grid-aligned rooms only, so the resulting numbers are re-derivable by hand.</summary>
        public static void Hunt()
        {
            var rng = new Random(20260720);
            int foundSpread = 0, foundCompact = 0;
            for (int trial = 0; trial < 300000 && (foundSpread < 4 || foundCompact < 4); trial++)
            {
                int nc = 2 + rng.Next(2);
                var contour = new InteriorFloor { NextRoomId = nc + 1 };
                for (int i = 0; i < nc; i++)
                {
                    int w = 4 + rng.Next(2) * 4, h = 4 + rng.Next(2) * 4;
                    int cx = 56 + rng.Next(4) * 2, cy = 56 + rng.Next(6) * 2;
                    contour.Rooms.Add(R(i + 1, cx, cy, w, h));
                }
                if (!ContourConnected(contour, M)) continue;

                int n = 4 + rng.Next(2);
                var floor = new InteriorFloor { NextRoomId = n + 1 };
                for (int i = 0; i < n; i++)
                    floor.Rooms.Add(R(i + 1, 64, 64, 4 + rng.Next(3), 4 + rng.Next(3)));
                floor.Rooms[0].SizeW = 4; floor.Rooms[0].SizeH = 4; floor.Rooms[0].TypeId = 2;
                for (int i = 1; i < n; i++) floor.Links.Add(new Link { RoomA = floor.Rooms[i].Id, RoomB = floor.Rooms[rng.Next(0, i)].Id });

                float colX = contour.Rooms[0].X * T, colY = contour.Rooms[0].Y * T;
                var a = Clone(floor); var b = Clone(floor);
                int nCompact = CompactOnlyLayout.PackAroundColumnWithinFootprint(a, 1, colX, colY, Clone(contour), M);
                int nSpread = SpreadOnlyLayout.PackAroundColumnWithinFootprint(b, 1, colX, colY, Clone(contour), M);
                if (nCompact == nSpread) continue;
                bool compactWins = nCompact > nSpread;
                if (compactWins && foundCompact >= 4) continue;
                if (!compactWins && foundSpread >= 4) continue;
                if (compactWins) foundCompact++; else foundSpread++;

                Console.WriteLine($"HIT ({(compactWins ? "COMPACT" : "SPREAD")} wins) trial {trial}: compact {nCompact} spread {nSpread}");
                Console.Write("  contour:");
                foreach (var r in contour.Rooms) Console.Write($" [{r.Id} {r.SizeW}x{r.SizeH} @({r.X * T:F1},{r.Y * T:F1})]");
                Console.WriteLine();
                Console.Write("  floor:  ");
                foreach (var r in floor.Rooms) Console.Write($" [{r.Id} {r.SizeW}x{r.SizeH}]");
                Console.Write("  links:");
                foreach (var l in floor.Links) Console.Write($" {l.RoomA}-{l.RoomB}");
                Console.WriteLine($"   column at ({colX},{colY})");
            }
            Console.WriteLine($"hunt done: {foundSpread} spread-wins, {foundCompact} compact-wins");
        }

        /// <summary>Search small grid-aligned fixtures where the SHIPPED packer and one MUTANT disagree — the
        /// raw material for a non-vacuous assertion. Reports the layout of both so the fixture can be lifted
        /// into CompactLayoutSelfTests with hand-checkable numbers.</summary>
        public static void HuntMutant(string which)
        {
            PackFn mut;
            switch (which)
            {
                case "anchor-outer": mut = MutAnchorOuter.PackAroundColumnWithinFootprint; break;
                case "link-pref": mut = MutNoLinkPref.PackAroundColumnWithinFootprint; break;
                case "tight-bounds": mut = MutTightBounds.PackAroundColumnWithinFootprint; break;
                default: Console.WriteLine("which = anchor-outer | link-pref | tight-bounds"); return;
            }
            var rng = new Random(20260720);
            int found = 0;
            for (int trial = 0; trial < 400000 && found < 8; trial++)
            {
                int nc = 1 + rng.Next(3);
                var contour = new InteriorFloor { NextRoomId = nc + 1 };
                for (int i = 0; i < nc; i++)
                {
                    int w = 4 + rng.Next(4) * 4, h = 4 + rng.Next(3) * 4;
                    int cx = 56 + rng.Next(6) * 2, cy = 56 + rng.Next(6) * 2;
                    contour.Rooms.Add(R(i + 1, cx, cy, w, h));
                }
                if (!ContourConnected(contour, M)) continue;

                int n = 3 + rng.Next(3);
                var floor = new InteriorFloor { NextRoomId = n + 1 };
                for (int i = 0; i < n; i++)
                    floor.Rooms.Add(R(i + 1, 64, 64, 4 + rng.Next(3), 4 + rng.Next(3)));
                floor.Rooms[0].SizeW = 4; floor.Rooms[0].SizeH = 4; floor.Rooms[0].TypeId = 2;
                for (int i = 1; i < n; i++) floor.Links.Add(new Link { RoomA = floor.Rooms[i].Id, RoomB = floor.Rooms[rng.Next(0, i)].Id });

                float colX = contour.Rooms[0].X * T, colY = contour.Rooms[0].Y * T;
                var a = Clone(floor); var b = Clone(floor);
                int nA = CompactLayout.PackAroundColumnWithinFootprint(a, 1, colX, colY, Clone(contour), M);
                int nB = mut(b, 1, colX, colY, Clone(contour), M);
                if (!Differs(a, b)) continue;
                // Optional extra filter for the assertion-22 fixture: the room the two orders disagree about
                // must be at a POSITIVE distance in the shipped run too, and STRICTLY nearer than in the mutant —
                // that pins the d ordering for corridor lengths, not just "flush beats non-flush".
                if (which == "anchor-outer" && !NearerGap(a, b)) continue;
                found++;
                Console.WriteLine($"HIT trial {trial} (kept {nA} vs mutant {nB})");
                Console.Write("  contour:");
                foreach (var r in contour.Rooms) Console.Write($" [{r.Id} {r.SizeW}x{r.SizeH} @({r.X * T:F1},{r.Y * T:F1})]");
                Console.WriteLine();
                Console.Write("  floor:  ");
                foreach (var r in floor.Rooms) Console.Write($" [{r.Id} {r.SizeW}x{r.SizeH}]");
                Console.Write("  links:");
                foreach (var l in floor.Links) Console.Write($" {l.RoomA}-{l.RoomB}");
                Console.WriteLine($"   column at ({colX},{colY})");
                Console.WriteLine("    SHIPPED " + Desc(a, nA));
                Console.WriteLine("    MUTANT  " + Desc(b, nB));
            }
            Console.WriteLine($"hunt-mutant {which}: {found} hits");
        }

        // Smallest Chebyshev edge gap between room `id` and any other kept room (0 = flush, >0 = corridor).
        static float MinGap(InteriorFloor f, int id)
        {
            var r = f.GetRoom(id);
            var (rw, rh) = DungeonProjection.EffectiveSize(r);
            float best = float.MaxValue;
            foreach (var o in f.Rooms)
            {
                if (o.Id == id) continue;
                var (ow, oh) = DungeonProjection.EffectiveSize(o);
                float gx = Math.Abs((r.X - o.X) * T) - (rw + ow) * 0.5f;
                float gy = Math.Abs((r.Y - o.Y) * T) - (rh + oh) * 0.5f;
                float g = Math.Max(gx, gy);
                if (g < best) best = g;
            }
            return best;
        }

        // True iff some room kept by BOTH runs sits at a positive gap in `a` and a strictly larger gap in `b`.
        static bool NearerGap(InteriorFloor a, InteriorFloor b)
        {
            foreach (var r in a.Rooms)
            {
                if (b.GetRoom(r.Id) == null) continue;
                float ga = MinGap(a, r.Id), gb = MinGap(b, r.Id);
                if (ga > 0.02f && gb > ga + 0.02f) return true;
            }
            return false;
        }

        static bool Differs(InteriorFloor a, InteriorFloor b)
        {
            if (a.Rooms.Count != b.Rooms.Count || a.Links.Count != b.Links.Count) return true;
            foreach (var r in a.Rooms)
            {
                var o = b.GetRoom(r.Id);
                if (o == null || o.X != r.X || o.Y != r.Y) return true;
            }
            return false;
        }

        /// <summary>Run one fixture through the TRACING copies of the shipped packer and of the anchor-outer
        /// mutant, printing every seed/fill placement — this is where the "anchor N at distance d" numbers in the
        /// self-test comments come from.</summary>
        public static void Trace(string name, InteriorFloor contour, InteriorFloor floor, float colX, float colY)
        {
            Console.WriteLine($"=== TRACE {name} ===");
            Console.WriteLine("SHIPPED:");
            var a = Clone(floor);
            int na = TraceLayout.PackAroundColumnWithinFootprint(a, 1, colX, colY, Clone(contour), M);
            Console.WriteLine("  -> " + Desc(a, na));
            Console.WriteLine("MUTANT anchor-outer:");
            var b = Clone(floor);
            int nb = TraceAnchorOuterLayout.PackAroundColumnWithinFootprint(b, 1, colX, colY, Clone(contour), M);
            Console.WriteLine("  -> " + Desc(b, nb));
        }

        public static void Run()
        {
            Console.WriteLine("=== M1: zig-zag contour, DISCONNECTED (shipped) vs CONNECTED (candidate) ===");
            var zzOld = new InteriorFloor { NextRoomId = 4 };
            zzOld.Rooms.Add(R(1, 60, 56, 8, 4)); zzOld.Rooms.Add(R(2, 56, 64, 4, 4)); zzOld.Rooms.Add(R(3, 60, 68, 4, 8));
            All("C(old, disconnected)", zzOld, ZigZagFloor(), 60f, 56f);
            All("C(new, connected)", ZigZagContourConnected(), ZigZagFloor(), 60f, 56f);

            Console.WriteLine();
            Console.WriteLine("=== I6: linked-anchor preference ===");
            // Column 1 (4x4) pinned at (64,64). Link 1-2 only (so the BFS reaches 2 and stops) plus 3-4.
            // Phase 2 seats 3 against the column (lowest id with a free flush side), then 4: its ONLY link is to
            // 3, and 3 has a free flush side — but room 2 (a LOWER id, unrelated) also has one.
            var g = new InteriorFloor { NextRoomId = 5 };
            for (int id = 1; id <= 4; id++) g.Rooms.Add(R(id, 64, 64, 4, 4));
            g.Links.Add(new Link { RoomA = 1, RoomB = 2 });
            g.Links.Add(new Link { RoomA = 3, RoomB = 4 });
            All("G: linked-anchor", StripContour(), g, 64f, 64f);

            Console.WriteLine();
            Console.WriteLine("=== C/D: connected contours where the two runs disagree ===");
            // C: SPREAD wins (hunt trial 966) — three overlapping arms, star topology from the column.
            var cc = new InteriorFloor { NextRoomId = 4 };
            cc.Rooms.Add(R(1, 60, 56, 4, 8)); cc.Rooms.Add(R(2, 62, 66, 8, 8)); cc.Rooms.Add(R(3, 60, 60, 8, 8));
            var cf = new InteriorFloor { NextRoomId = 6 };
            cf.Rooms.Add(R(1, 60, 56, 4, 4)); cf.Rooms.Add(R(2, 60, 56, 6, 5)); cf.Rooms.Add(R(3, 60, 56, 4, 4));
            cf.Rooms.Add(R(4, 60, 56, 5, 4)); cf.Rooms.Add(R(5, 60, 56, 4, 5));
            for (int id = 2; id <= 5; id++) cf.Links.Add(new Link { RoomA = id, RoomB = 1 });
            Console.WriteLine("  contour connected: " + ContourConnected(cc, M));
            All("C: spread wins", cc, cf, 60f, 56f);

            // D: COMPACT wins (hunt trial 256) — two overlapping arms (an L).
            var dc = new InteriorFloor { NextRoomId = 3 };
            dc.Rooms.Add(R(1, 58, 56, 8, 4)); dc.Rooms.Add(R(2, 56, 62, 8, 8));
            var df = new InteriorFloor { NextRoomId = 6 };
            df.Rooms.Add(R(1, 58, 56, 4, 4)); df.Rooms.Add(R(2, 58, 56, 6, 4)); df.Rooms.Add(R(3, 58, 56, 4, 4));
            df.Rooms.Add(R(4, 58, 56, 5, 5)); df.Rooms.Add(R(5, 58, 56, 5, 4));
            df.Links.Add(new Link { RoomA = 2, RoomB = 1 }); df.Links.Add(new Link { RoomA = 3, RoomB = 1 });
            df.Links.Add(new Link { RoomA = 4, RoomB = 2 }); df.Links.Add(new Link { RoomA = 5, RoomB = 4 });
            Console.WriteLine("  contour connected: " + ContourConnected(dc, M));
            All("D: compact wins", dc, df, 58f, 56f);

            Console.WriteLine();
            Console.WriteLine("=== I2: distance-outer (hunt trial 5947) ===");
            var e2c = new InteriorFloor { NextRoomId = 4 };
            e2c.Rooms.Add(R(1, 64, 64, 12, 4)); e2c.Rooms.Add(R(2, 64, 56, 16, 4)); e2c.Rooms.Add(R(3, 56, 56, 12, 12));
            var e2f = new InteriorFloor { NextRoomId = 4 };
            e2f.Rooms.Add(R(1, 64, 64, 4, 4)); e2f.Rooms.Add(R(2, 64, 64, 4, 5)); e2f.Rooms.Add(R(3, 64, 64, 6, 6));
            e2f.Links.Add(new Link { RoomA = 2, RoomB = 1 }); e2f.Links.Add(new Link { RoomA = 3, RoomB = 1 });
            Console.WriteLine("  contour connected: " + ContourConnected(e2c, M));
            All("E: distance-outer", e2c, e2f, 64f, 64f);
            Trace("E: distance-outer", e2c, e2f, 64f, 64f);

            Console.WriteLine();
            // I2 candidate found by `huntmut anchor-outer` (trial 290).
            var i2c = new InteriorFloor { NextRoomId = 4 };
            i2c.Rooms.Add(R(1, 62, 66, 4, 4)); i2c.Rooms.Add(R(2, 58, 66, 4, 8)); i2c.Rooms.Add(R(3, 64, 56, 12, 8));
            var i2f = new InteriorFloor { NextRoomId = 5 };
            i2f.Rooms.Add(R(1, 62, 66, 4, 4)); i2f.Rooms.Add(R(2, 62, 66, 5, 4));
            i2f.Rooms.Add(R(3, 62, 66, 6, 4)); i2f.Rooms.Add(R(4, 62, 66, 4, 4));
            i2f.Links.Add(new Link { RoomA = 2, RoomB = 1 });
            i2f.Links.Add(new Link { RoomA = 3, RoomB = 2 });
            i2f.Links.Add(new Link { RoomA = 4, RoomB = 2 });
            All("I2 candidate", i2c, i2f, 62f, 66f);
            Trace("I2 candidate", i2c, i2f, 62f, 66f);

            Console.WriteLine();
            Console.WriteLine("=== I4: a room flush against the contour's OUTER edge ===");
            // EdgeStripContour's footprint is [51,78] x [60.5,67.5]; the flush chain right of the column at 64
            // lands rooms at 68, 72 and 76 — the last spans x[74,78], its right edge EXACTLY on the outer edge.
            var h = new InteriorFloor { NextRoomId = 5 };
            for (int id = 1; id <= 4; id++) h.Rooms.Add(R(id, 64, 64, 4, 4));
            h.Links.Add(new Link { RoomA = 1, RoomB = 2 });
            h.Links.Add(new Link { RoomA = 2, RoomB = 3 });
            h.Links.Add(new Link { RoomA = 3, RoomB = 4 });
            All("H: flush to outer edge", EdgeStripContour(), h, 64f, 64f);
        }
    }
}
